name: test

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node.yml@main
    with:
      range: '>= 6'
      command: npm run test-main
