name: test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dcodeIO/setup-node-nvm@v5
        with:
          node-version: iojs
      - run: npm install
      - run: npm test
